require('dotenv').config();
const mongoose = require('mongoose');
const User = require('../models/User');
const Product = require('../models/Product');
const Discount = require('../models/Discount');
const Seller = require('../models/Seller');

const products = [
    // ===== ELECTRONICS (10) =====
    { name: 'Premium Wireless Headphones', description: 'High-fidelity wireless headphones with ANC, 40-hour battery life.', category: 'Electronics', price: 16599, basePrice: 24899, stockQuantity: 45, imageURL: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=400&fit=crop', brand: 'SoundMax', tags: ['wireless', 'noise-cancelling'], averageRating: 4.5, numReviews: 128, salesLast30Days: 45 },
    { name: 'Smart Fitness Watch Pro', description: 'Advanced fitness tracker with GPS, heart rate monitor, blood oxygen, 7-day battery.', category: 'Electronics', price: 12449, basePrice: 20749, stockQuantity: 75, imageURL: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=400&fit=crop', brand: 'FitTech', tags: ['fitness', 'smartwatch'], averageRating: 4.6, numReviews: 215, salesLast30Days: 67 },
    { name: 'Portable Bluetooth Speaker', description: 'Waterproof 360° sound, 20hr battery. IP67 rated for pool & beach.', category: 'Electronics', price: 3486, basePrice: 6639, stockQuantity: 100, seasonalTag: 'Summer', imageURL: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&h=400&fit=crop', brand: 'SoundMax', tags: ['speaker', 'waterproof'], averageRating: 4.3, numReviews: 94, salesLast30Days: 52 },
    { name: 'Wireless Earbuds Ultra', description: 'True wireless with deep bass, touch controls, 30hr case battery, IPX5.', category: 'Electronics', price: 4979, basePrice: 8299, stockQuantity: 150, imageURL: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=500&h=400&fit=crop', brand: 'SoundMax', tags: ['earbuds', 'wireless'], averageRating: 4.4, numReviews: 340, salesLast30Days: 89 },
    { name: '4K Webcam with Ring Light', description: 'Ultra HD webcam with noise-cancelling mic, auto-focus, adjustable ring light.', category: 'Electronics', price: 5809, basePrice: 9959, stockQuantity: 60, imageURL: 'https://m.media-amazon.com/images/I/61X+LxaKQTL._SL500_.jpg', brand: 'TechView', tags: ['webcam', 'streaming'], averageRating: 4.2, numReviews: 78, salesLast30Days: 23 },
    { name: 'USB-C Hub 7-in-1', description: 'HDMI 4K, USB 3.0, SD reader, PD charging. Works with all laptops.', category: 'Electronics', price: 2904, basePrice: 4979, stockQuantity: 200, imageURL: 'https://m.media-amazon.com/images/I/61EHEgZqnUL._SL500_.jpg', brand: 'DeskPro', tags: ['usb-c', 'adapter'], averageRating: 4.5, numReviews: 189, salesLast30Days: 55 },
    { name: 'Mechanical Gaming Keyboard', description: 'RGB Cherry MX switches, per-key lighting, hot-swappable, Bluetooth 5.0.', category: 'Electronics', price: 7885, basePrice: 13279, stockQuantity: 70, imageURL: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&h=400&fit=crop', brand: 'KeyMaster', tags: ['mechanical', 'gaming'], averageRating: 4.7, numReviews: 156, salesLast30Days: 38 },
    { name: 'Wireless Charging Pad', description: 'Fast Qi charger for iPhone, Samsung. Sleek aluminum design, LED indicator.', category: 'Electronics', price: 1659, basePrice: 3319, stockQuantity: 250, imageURL: 'https://m.media-amazon.com/images/I/51GJyVgJURL._SL500_.jpg', brand: 'ChargePro', tags: ['charger', 'wireless'], averageRating: 4.3, numReviews: 210, salesLast30Days: 72 },
    { name: 'Laptop Backpack Anti-Theft', description: 'Water-resistant backpack with USB port, padded laptop compartment, RFID pocket.', category: 'Electronics', price: 3734, basePrice: 6224, stockQuantity: 120, imageURL: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=400&fit=crop', brand: 'TechCarry', tags: ['backpack', 'anti-theft'], averageRating: 4.4, numReviews: 167, salesLast30Days: 41 },
    { name: 'Smart Home Mini Speaker', description: 'Voice assistant compatible smart speaker with premium sound, compact design.', category: 'Electronics', price: 2489, basePrice: 4564, stockQuantity: 180, imageURL: 'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=500&h=400&fit=crop', brand: 'HomeTech', tags: ['smart', 'speaker'], averageRating: 4.1, numReviews: 234, salesLast30Days: 63 },

    // ===== CLOTHING (10) =====
    { name: 'Organic Cotton Hoodie', description: 'Sustainable organic cotton with relaxed fit, kangaroo pocket, brushed fleece.', category: 'Clothing', price: 3735, basePrice: 6639, stockQuantity: 200, seasonalTag: 'Winter', imageURL: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500&h=400&fit=crop', brand: 'EcoWear', tags: ['organic', 'winter'], averageRating: 4.4, numReviews: 73, salesLast30Days: 28 },
    { name: 'Summer Linen Dress', description: 'Breathable 100% linen in oceanic blue. Perfect for warm weather.', category: 'Clothing', price: 3984, basePrice: 7469, stockQuantity: 110, seasonalTag: 'Summer', imageURL: 'https://m.media-amazon.com/images/I/61tGAtzuH1L._SL500_.jpg', brand: 'LinenLux', tags: ['linen', 'summer'], averageRating: 4.1, numReviews: 56, salesLast30Days: 19 },
    { name: 'Classic Denim Jacket', description: 'Vintage wash denim jacket. Button closure, chest pockets, unisex fit.', category: 'Clothing', price: 4979, basePrice: 8299, stockQuantity: 85, imageURL: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&h=400&fit=crop', brand: 'DenimCo', tags: ['denim', 'classic'], averageRating: 4.5, numReviews: 132, salesLast30Days: 41 },
    { name: 'Running Performance Tee', description: 'Moisture-wicking athletic tee with 4-way stretch. Lightweight for workouts.', category: 'Clothing', price: 2074, basePrice: 3734, stockQuantity: 300, seasonalTag: 'Spring', imageURL: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=400&fit=crop', brand: 'ActiveFit', tags: ['athletic', 'moisture-wicking'], averageRating: 4.3, numReviews: 98, salesLast30Days: 56 },
    { name: 'Oversized Knit Sweater', description: 'Chunky knit in cream. Soft wool blend, ribbed cuffs, cozy oversized.', category: 'Clothing', price: 4565, basePrice: 8299, stockQuantity: 130, seasonalTag: 'Winter', isClearance: true, imageURL: 'https://m.media-amazon.com/images/I/71USqAuXf+L._SL500_.jpg', brand: 'KnitCo', tags: ['knit', 'clearance'], averageRating: 4.0, numReviews: 42, salesLast30Days: 15 },
    { name: 'Formal Slim Fit Shirt', description: 'Wrinkle-free cotton blend dress shirt. Spread collar, slim cut.', category: 'Clothing', price: 3319, basePrice: 5809, stockQuantity: 150, imageURL: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500&h=400&fit=crop', brand: 'ClassicFit', tags: ['formal', 'slim-fit'], averageRating: 4.4, numReviews: 87, salesLast30Days: 33 },
    { name: 'Leather Belt Premium', description: 'Genuine Italian leather, brushed silver buckle. 35mm, reversible black/brown.', category: 'Clothing', price: 2489, basePrice: 4564, stockQuantity: 180, imageURL: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=500&h=400&fit=crop', brand: 'LeatherCraft', tags: ['leather', 'premium'], averageRating: 4.6, numReviews: 145, salesLast30Days: 38 },
    { name: 'Canvas Sneakers Classic', description: 'Low-top canvas sneakers with vulcanized rubber sole. Everyday comfort.', category: 'Clothing', price: 2904, basePrice: 4979, stockQuantity: 220, imageURL: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500&h=400&fit=crop', brand: 'StreetStyle', tags: ['sneakers', 'casual'], averageRating: 4.3, numReviews: 267, salesLast30Days: 78 },
    { name: 'Wool Blend Scarf', description: 'Soft wool blend scarf in charcoal grey. Oversized wrap style, 200cm length.', category: 'Clothing', price: 1659, basePrice: 2904, stockQuantity: 160, seasonalTag: 'Winter', imageURL: 'https://m.media-amazon.com/images/I/71jjLjYk1gL._SL500_.jpg', brand: 'WarmWrap', tags: ['scarf', 'winter'], averageRating: 4.2, numReviews: 67, salesLast30Days: 24 },
    { name: 'Aviator Sunglasses', description: 'UV400 polarized aviator sunglasses with metal frame. Unisex design.', category: 'Clothing', price: 1908, basePrice: 3734, stockQuantity: 190, seasonalTag: 'Summer', imageURL: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&h=400&fit=crop', brand: 'ShadesCo', tags: ['sunglasses', 'polarized'], averageRating: 4.5, numReviews: 189, salesLast30Days: 67 },

    // ===== HOME & KITCHEN (10) =====
    { name: 'Ceramic Pour-Over Coffee Set', description: 'Handcrafted ceramic dripper with thermal carafe for perfect pour-over coffee.', category: 'Home & Kitchen', price: 2905, basePrice: 5394, stockQuantity: 90, seasonalTag: 'Fall', imageURL: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500&h=400&fit=crop', brand: 'BrewCraft', tags: ['coffee', 'ceramic'], averageRating: 4.8, numReviews: 201, salesLast30Days: 43 },
    { name: 'Smart LED Desk Lamp', description: 'Touch-controlled, 5 color temps, wireless charging base, USB-C port.', category: 'Home & Kitchen', price: 3154, basePrice: 5809, stockQuantity: 95, imageURL: 'https://m.media-amazon.com/images/I/61mlYfC8biL._SL500_.jpg', brand: 'LumiTech', tags: ['LED', 'smart'], averageRating: 4.3, numReviews: 89, salesLast30Days: 21 },
    { name: 'Weighted Blanket Premium', description: '15lb with cooling bamboo cover. Deep pressure therapy for better sleep.', category: 'Home & Kitchen', price: 5395, basePrice: 9959, stockQuantity: 55, seasonalTag: 'Winter', imageURL: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=500&h=400&fit=crop', brand: 'DreamWeave', tags: ['sleep', 'bamboo'], averageRating: 4.5, numReviews: 167, salesLast30Days: 29 },
    { name: 'Stainless Steel Cookware Set', description: '10-piece tri-ply stainless steel. Induction compatible, oven safe 500°F.', category: 'Home & Kitchen', price: 10789, basePrice: 19089, stockQuantity: 40, imageURL: 'https://images.unsplash.com/photo-1584990347449-a2d4c2c044c9?w=500&h=400&fit=crop', brand: 'ChefPro', tags: ['cookware', 'stainless'], averageRating: 4.7, numReviews: 134, salesLast30Days: 18 },
    { name: 'Bamboo Cutting Board Set', description: 'Set of 3 organic bamboo boards with juice grooves. Anti-bacterial.', category: 'Home & Kitchen', price: 1908, basePrice: 3319, stockQuantity: 180, imageURL: 'https://m.media-amazon.com/images/I/81Y5yYJDfkL._SL500_.jpg', brand: 'EcoKitchen', tags: ['bamboo', 'eco'], averageRating: 4.4, numReviews: 98, salesLast30Days: 35 },
    { name: 'Aromatherapy Diffuser', description: 'Ultrasonic essential oil diffuser with color-changing LED. 300ml, auto shut-off.', category: 'Home & Kitchen', price: 2323, basePrice: 4149, stockQuantity: 120, imageURL: 'https://m.media-amazon.com/images/I/61s9CbM5qnL._SL500_.jpg', brand: 'AromaBliss', tags: ['diffuser', 'relaxation'], averageRating: 4.5, numReviews: 176, salesLast30Days: 44 },
    { name: 'Indoor Plant Pot Set', description: 'Set of 4 modern ceramic pots with drainage & bamboo saucers. Matte finish.', category: 'Home & Kitchen', price: 2738, basePrice: 4564, stockQuantity: 95, imageURL: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=500&h=400&fit=crop', brand: 'GreenHome', tags: ['plants', 'decor'], averageRating: 4.6, numReviews: 112, salesLast30Days: 27 },
    { name: 'Electric Kettle Glass', description: '1.7L glass kettle with LED, auto shut-off, boil-dry protection. BPA-free.', category: 'Home & Kitchen', price: 2655, basePrice: 4564, stockQuantity: 110, imageURL: 'https://m.media-amazon.com/images/I/61sK4Y8LIgL._SL500_.jpg', brand: 'BrewCraft', tags: ['kettle', 'glass'], averageRating: 4.4, numReviews: 156, salesLast30Days: 38 },
    { name: 'Memory Foam Pillow Set', description: 'Set of 2 cooling gel memory foam pillows. Hypoallergenic, washable cover.', category: 'Home & Kitchen', price: 3319, basePrice: 5809, stockQuantity: 85, imageURL: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=500&h=400&fit=crop', brand: 'DreamWeave', tags: ['pillow', 'memory-foam'], averageRating: 4.6, numReviews: 198, salesLast30Days: 52 },
    { name: 'Cast Iron Skillet 12-inch', description: 'Pre-seasoned cast iron skillet. Oven safe, works on all cooktops including induction.', category: 'Home & Kitchen', price: 2406, basePrice: 4149, stockQuantity: 100, imageURL: 'https://m.media-amazon.com/images/I/81Ul8MZGGKL._SL500_.jpg', brand: 'ChefPro', tags: ['cast-iron', 'skillet'], averageRating: 4.8, numReviews: 234, salesLast30Days: 47 },

    // ===== SPORTS (10) =====
    { name: 'Running Shoes CloudStride', description: 'Cloud-cushion sole tech. Lightweight for road runners seeking performance.', category: 'Sports', price: 7055, basePrice: 11619, stockQuantity: 160, seasonalTag: 'Spring', imageURL: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=400&fit=crop', brand: 'StrideMax', tags: ['running', 'performance'], averageRating: 4.6, numReviews: 312, salesLast30Days: 78 },
    { name: 'Yoga Mat Professional', description: 'Non-slip with alignment lines. Eco-friendly TPE, 6mm for joint protection.', category: 'Sports', price: 2324, basePrice: 4564, stockQuantity: 140, seasonalTag: 'Spring', imageURL: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&h=400&fit=crop', brand: 'ZenFit', tags: ['yoga', 'eco'], averageRating: 4.4, numReviews: 145, salesLast30Days: 34 },
    { name: 'Stainless Steel Water Bottle', description: 'Vacuum insulated. Cold 24hrs, hot 12hrs. BPA-free, 32oz.', category: 'Sports', price: 1162, basePrice: 2489, stockQuantity: 250, seasonalTag: 'Summer', imageURL: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500&h=400&fit=crop', brand: 'HydroElite', tags: ['insulated', 'BPA-free'], averageRating: 4.2, numReviews: 198, salesLast30Days: 62 },
    { name: 'Resistance Bands Set', description: '5-pack with handles, door anchor, carry bag. Multi-strength levels.', category: 'Sports', price: 1576, basePrice: 2904, stockQuantity: 200, imageURL: 'https://m.media-amazon.com/images/I/71la3zY4G3L._SL500_.jpg', brand: 'FlexFit', tags: ['resistance', 'workout'], averageRating: 4.5, numReviews: 223, salesLast30Days: 61 },
    { name: 'Foam Roller Recovery', description: 'High-density 18-inch roller for muscle recovery and deep tissue massage.', category: 'Sports', price: 1825, basePrice: 3319, stockQuantity: 110, imageURL: 'https://m.media-amazon.com/images/I/61jFgUUllHL._SL500_.jpg', brand: 'RecoverPro', tags: ['recovery', 'massage'], averageRating: 4.3, numReviews: 87, salesLast30Days: 25 },
    { name: 'Gym Duffel Bag', description: 'Spacious with shoe compartment, wet pocket, adjustable strap. Water-resistant.', category: 'Sports', price: 2738, basePrice: 4979, stockQuantity: 90, imageURL: 'https://m.media-amazon.com/images/I/81DCYdR5PIL._SL500_.jpg', brand: 'ActiveGear', tags: ['gym', 'duffel'], averageRating: 4.4, numReviews: 156, salesLast30Days: 42 },
    { name: 'Jump Rope Speed Pro', description: 'Ball-bearing speed rope with adjustable length, anti-slip handles. For HIIT.', category: 'Sports', price: 1078, basePrice: 2074, stockQuantity: 300, imageURL: 'https://m.media-amazon.com/images/I/71PgJgWqFIL._SL500_.jpg', brand: 'CardioMax', tags: ['jump-rope', 'cardio'], averageRating: 4.5, numReviews: 267, salesLast30Days: 73 },
    { name: 'Wrist Wraps Weightlifting', description: 'Heavy-duty wrist support wraps, 18-inch. Thumb loop, Velcro closure. Pair.', category: 'Sports', price: 829, basePrice: 1659, stockQuantity: 350, imageURL: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&h=400&fit=crop', brand: 'IronGrip', tags: ['weightlifting', 'support'], averageRating: 4.3, numReviews: 189, salesLast30Days: 54 },
    { name: 'Cycling Gloves Padded', description: 'Half-finger cycling gloves with gel padding and breathable mesh. Anti-slip grip.', category: 'Sports', price: 1327, basePrice: 2489, stockQuantity: 170, imageURL: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=500&h=400&fit=crop', brand: 'RideMax', tags: ['cycling', 'gloves'], averageRating: 4.2, numReviews: 98, salesLast30Days: 31 },
    { name: 'Sports Compression Socks', description: '3-pack graduated compression socks for running, travel, and recovery. Unisex.', category: 'Sports', price: 1410, basePrice: 2489, stockQuantity: 240, imageURL: 'https://m.media-amazon.com/images/I/81j3DNiH6HL._SL500_.jpg', brand: 'FlexFit', tags: ['compression', 'socks'], averageRating: 4.4, numReviews: 145, salesLast30Days: 48 },

    // ===== BEAUTY (10) =====
    { name: 'Natural Skincare Gift Set', description: '5-product organic set: cleanser, toner, serum, moisturizer, clay mask.', category: 'Beauty', price: 4316, basePrice: 7469, stockQuantity: 85, imageURL: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=400&fit=crop', brand: 'PureGlow', tags: ['organic', 'gift-set'], averageRating: 4.5, numReviews: 178, salesLast30Days: 41 },
    { name: 'Rose Gold Makeup Brush Set', description: '12-piece professional set with vegan bristles, rose gold handles & pouch.', category: 'Beauty', price: 2074, basePrice: 3734, stockQuantity: 120, imageURL: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=500&h=400&fit=crop', brand: 'GlamTools', tags: ['makeup', 'brushes'], averageRating: 4.6, numReviews: 234, salesLast30Days: 58 },
    { name: 'Vitamin C Brightening Serum', description: '30ml with hyaluronic acid. Brightens, reduces dark spots, anti-aging.', category: 'Beauty', price: 1576, basePrice: 2904, stockQuantity: 200, imageURL: 'https://m.media-amazon.com/images/I/61seMnMEU0L._SL500_.jpg', brand: 'PureGlow', tags: ['serum', 'vitamin-c'], averageRating: 4.7, numReviews: 312, salesLast30Days: 87 },
    { name: 'Hair Care Repair Kit', description: 'Sulfate-free shampoo, conditioner & mask. Argan oil and keratin infused.', category: 'Beauty', price: 2489, basePrice: 4149, stockQuantity: 95, imageURL: 'https://images.unsplash.com/photo-1522338242992-e1a54571a695?w=500&h=400&fit=crop', brand: 'HairRevive', tags: ['haircare', 'repair'], averageRating: 4.3, numReviews: 145, salesLast30Days: 36 },
    { name: 'Jade Face Roller Set', description: 'Natural jade roller & gua sha. Reduces puffiness, promotes drainage.', category: 'Beauty', price: 1327, basePrice: 2489, stockQuantity: 175, imageURL: 'https://m.media-amazon.com/images/I/61Iv4v5FL4L._SL500_.jpg', brand: 'ZenBeauty', tags: ['jade', 'facial'], averageRating: 4.4, numReviews: 198, salesLast30Days: 49 },
    { name: 'Matte Lipstick Collection', description: 'Set of 6 long-lasting matte lipsticks in trending shades. Vegan formula.', category: 'Beauty', price: 1825, basePrice: 3319, stockQuantity: 140, imageURL: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500&h=400&fit=crop', brand: 'GlamTools', tags: ['lipstick', 'matte'], averageRating: 4.5, numReviews: 267, salesLast30Days: 62 },
    { name: 'Sheet Mask Variety Pack', description: '12-pack Korean sheet masks. Hydrating, brightening, anti-aging formulas.', category: 'Beauty', price: 1244, basePrice: 2323, stockQuantity: 200, imageURL: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=500&h=400&fit=crop', brand: 'K-Glow', tags: ['sheet-mask', 'korean'], averageRating: 4.6, numReviews: 189, salesLast30Days: 55 },
    { name: 'Nail Polish Set Pastel', description: '8-color pastel nail polish set. Quick-dry, chip-resistant, non-toxic formula.', category: 'Beauty', price: 1410, basePrice: 2489, stockQuantity: 160, imageURL: 'https://m.media-amazon.com/images/I/71YD8tlqLdL._SL500_.jpg', brand: 'NailArt', tags: ['nail-polish', 'pastel'], averageRating: 4.3, numReviews: 134, salesLast30Days: 39 },
    { name: 'Perfume Gift Set Mini', description: '5 mini designer-inspired perfumes, 10ml each. Floral, woody, fresh notes.', category: 'Beauty', price: 2904, basePrice: 4979, stockQuantity: 75, imageURL: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=500&h=400&fit=crop', brand: 'ScentLux', tags: ['perfume', 'gift'], averageRating: 4.7, numReviews: 156, salesLast30Days: 43 },
    { name: 'Electric Facial Cleansing Brush', description: 'Silicone face brush with 5 speeds. Waterproof IPX7, USB rechargeable.', category: 'Beauty', price: 2240, basePrice: 4149, stockQuantity: 100, imageURL: 'https://m.media-amazon.com/images/I/61-GmpPdGGL._SL500_.jpg', brand: 'PureGlow', tags: ['facial', 'cleansing'], averageRating: 4.4, numReviews: 112, salesLast30Days: 33 },

    // ===== BOOKS (10) =====
    { name: 'Vintage Leather Journal', description: 'Hand-bound leather, 240 pages acid-free paper. Brass clasp, ribbon bookmarks.', category: 'Books', price: 1494, basePrice: 2904, stockQuantity: 300, imageURL: 'https://m.media-amazon.com/images/I/91dls3OKLWL._SL500_.jpg', brand: 'HeritageBinds', tags: ['leather', 'journal'], averageRating: 4.7, numReviews: 234, salesLast30Days: 56 },
    { name: 'Bestseller Fiction Collection', description: 'Box set of 5 award-winning fiction novels. Perfect gift for book lovers.', category: 'Books', price: 3319, basePrice: 5809, stockQuantity: 60, imageURL: 'https://m.media-amazon.com/images/I/71C4LCJRePL._SL500_.jpg', brand: 'BookHaven', tags: ['fiction', 'collection'], averageRating: 4.8, numReviews: 167, salesLast30Days: 32 },
    { name: 'Cookbook - World Cuisine', description: '300+ recipes from 40 countries. Beautiful photography, step-by-step guides.', category: 'Books', price: 2406, basePrice: 4149, stockQuantity: 80, imageURL: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=500&h=400&fit=crop', brand: 'CulinaryPress', tags: ['cookbook', 'recipes'], averageRating: 4.6, numReviews: 89, salesLast30Days: 21 },
    { name: 'Sketchbook Artist Grade', description: '100-page heavyweight, 9x12 inch, acid-free. For pencil, charcoal, watercolor.', category: 'Books', price: 1078, basePrice: 2074, stockQuantity: 250, imageURL: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500&h=400&fit=crop', brand: 'ArtSupply', tags: ['sketch', 'art'], averageRating: 4.5, numReviews: 178, salesLast30Days: 44 },
    { name: 'Self-Help Bestsellers Pack', description: '3-book set: mindfulness, productivity, and personal finance essentials.', category: 'Books', price: 2738, basePrice: 4564, stockQuantity: 90, imageURL: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=500&h=400&fit=crop', brand: 'MindPress', tags: ['self-help', 'motivation'], averageRating: 4.4, numReviews: 212, salesLast30Days: 47 },
    { name: 'Children Picture Book Set', description: '10-book illustrated storybook collection. Ages 3-8, colorful & educational.', category: 'Books', price: 2074, basePrice: 3734, stockQuantity: 150, imageURL: 'https://m.media-amazon.com/images/I/81jYRD7pURL._SL500_.jpg', brand: 'KidsRead', tags: ['children', 'picture-book'], averageRating: 4.8, numReviews: 189, salesLast30Days: 53 },
    { name: 'Science Fiction Anthology', description: 'Collection of 15 classic sci-fi short stories. Asimov, Clarke, Dick & more.', category: 'Books', price: 1244, basePrice: 2323, stockQuantity: 120, imageURL: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500&h=400&fit=crop', brand: 'BookHaven', tags: ['sci-fi', 'anthology'], averageRating: 4.5, numReviews: 134, salesLast30Days: 29 },
    { name: 'Bullet Journal Starter Kit', description: 'Dotted journal with stencils, washi tape set, and colored pens. Gift box.', category: 'Books', price: 1825, basePrice: 3319, stockQuantity: 110, imageURL: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=500&h=400&fit=crop', brand: 'PlannerCo', tags: ['bullet-journal', 'kit'], averageRating: 4.6, numReviews: 198, salesLast30Days: 41 },
    { name: 'Travel Photography Book', description: 'Stunning 200-page coffee table book. Landscapes from 50 countries.', category: 'Books', price: 2904, basePrice: 4979, stockQuantity: 55, imageURL: 'https://images.unsplash.com/photo-1500964757637-c85e8a162699?w=500&h=400&fit=crop', brand: 'VisionPress', tags: ['photography', 'travel'], averageRating: 4.7, numReviews: 87, salesLast30Days: 19 },
    { name: 'Language Learning Workbook', description: 'Interactive Spanish workbook with exercises, QR audio codes. Beginner level.', category: 'Books', price: 1410, basePrice: 2489, stockQuantity: 170, imageURL: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=500&h=400&fit=crop', brand: 'LinguaBooks', tags: ['language', 'workbook'], averageRating: 4.3, numReviews: 156, salesLast30Days: 38 },

    // ===== GROCERY (10) =====
    { name: 'Artisan Dark Chocolate Collection', description: '12-piece single-origin dark chocolates from Ecuador, Ghana, Madagascar.', category: 'Grocery', price: 2075, basePrice: 3568, stockQuantity: 50, seasonalTag: 'Winter', expiryDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000), imageURL: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=500&h=400&fit=crop', brand: 'CocoaLux', tags: ['chocolate', 'artisan'], averageRating: 4.9, numReviews: 89, salesLast30Days: 35 },
    { name: 'Gourmet Tea Sampler', description: '20 premium loose-leaf teas with bamboo infuser. Darjeeling, Oolong, Matcha.', category: 'Grocery', price: 1660, basePrice: 3236, stockQuantity: 65, seasonalTag: 'Fall', expiryDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000), imageURL: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&h=400&fit=crop', brand: 'TeaVoyage', tags: ['tea', 'gourmet'], averageRating: 4.4, numReviews: 112, salesLast30Days: 27 },
    { name: 'Organic Honey Gift Box', description: '3 varieties of raw organic: wildflower, manuka, acacia. Glass jars.', category: 'Grocery', price: 2904, basePrice: 4564, stockQuantity: 70, expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000), imageURL: 'https://m.media-amazon.com/images/I/71eApVWJ3-L._SL500_.jpg', brand: 'NatureSweet', tags: ['honey', 'organic'], averageRating: 4.7, numReviews: 134, salesLast30Days: 31 },
    { name: 'Premium Mixed Nuts Pack', description: 'Roasted almonds, cashews, macadamia, pecans, walnuts. 2lb bag.', category: 'Grocery', price: 1410, basePrice: 2406, stockQuantity: 150, expiryDate: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000), imageURL: 'https://m.media-amazon.com/images/I/81WWUUX1XML._SL500_.jpg', brand: 'NutHaven', tags: ['nuts', 'snacks'], averageRating: 4.5, numReviews: 210, salesLast30Days: 58 },
    { name: 'Italian Pasta Gift Set', description: 'Premium set with 4 artisan pastas, truffle oil, and sundried tomato pesto.', category: 'Grocery', price: 2489, basePrice: 4149, stockQuantity: 60, expiryDate: new Date(Date.now() + 200 * 24 * 60 * 60 * 1000), imageURL: 'https://images.unsplash.com/photo-1551462147-37885acc36f1?w=500&h=400&fit=crop', brand: 'ItaliaCo', tags: ['pasta', 'italian'], averageRating: 4.6, numReviews: 78, salesLast30Days: 22 },
    { name: 'Organic Green Tea Matcha', description: 'Ceremonial grade matcha powder. 100g package with bamboo whisk.', category: 'Grocery', price: 1908, basePrice: 3319, stockQuantity: 100, expiryDate: new Date(Date.now() + 240 * 24 * 60 * 60 * 1000), imageURL: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=500&h=400&fit=crop', brand: 'TeaVoyage', tags: ['matcha', 'organic'], averageRating: 4.5, numReviews: 167, salesLast30Days: 45 },
    { name: 'Dried Fruit & Berry Mix', description: 'Premium blend of dried mango, cranberries, blueberries, and apricots. 500g.', category: 'Grocery', price: 1078, basePrice: 1908, stockQuantity: 200, expiryDate: new Date(Date.now() + 150 * 24 * 60 * 60 * 1000), imageURL: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500&h=400&fit=crop', brand: 'FruitFarm', tags: ['dried-fruit', 'snacks'], averageRating: 4.3, numReviews: 145, salesLast30Days: 52 },
    { name: 'Artisan Coffee Beans', description: 'Single-origin medium roast coffee beans. Notes of caramel & citrus. 500g bag.', category: 'Grocery', price: 1576, basePrice: 2738, stockQuantity: 130, expiryDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000), imageURL: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500&h=400&fit=crop', brand: 'BrewCraft', tags: ['coffee', 'beans'], averageRating: 4.7, numReviews: 198, salesLast30Days: 61 },
    { name: 'Spice Collection Gift Box', description: '12 premium spices in glass jars with wooden rack. From around the world.', category: 'Grocery', price: 2323, basePrice: 3983, stockQuantity: 80, expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000), imageURL: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&h=400&fit=crop', brand: 'SpiceWorld', tags: ['spices', 'gift'], averageRating: 4.6, numReviews: 112, salesLast30Days: 28 },
    { name: 'Protein Granola Bar Pack', description: '12-pack protein granola bars. Dark chocolate, almond & oat. No added sugar.', category: 'Grocery', price: 1244, basePrice: 2074, stockQuantity: 180, expiryDate: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000), imageURL: 'https://m.media-amazon.com/images/I/81l+B9GodiL._SL500_.jpg', brand: 'FitFuel', tags: ['protein', 'granola'], averageRating: 4.4, numReviews: 234, salesLast30Days: 67 },

    // ===== TOYS (10) =====
    { name: 'Building Blocks Set 500pc', description: '12 vibrant colors, compatible with major brands. Ages 4+.', category: 'Toys', price: 1826, basePrice: 3734, stockQuantity: 180, imageURL: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=500&h=400&fit=crop', brand: 'BrickWiz', tags: ['building', 'educational'], averageRating: 4.6, numReviews: 267, salesLast30Days: 48 },
    { name: 'Plush Unicorn Large', description: 'Ultra-soft 14-inch plush unicorn. Machine washable, hypoallergenic.', category: 'Toys', price: 1410, basePrice: 2489, stockQuantity: 200, imageURL: 'https://m.media-amazon.com/images/I/71spStf7e4L._SL500_.jpg', brand: 'CuddlePals', tags: ['plush', 'gift'], averageRating: 4.8, numReviews: 189, salesLast30Days: 55 },
    { name: 'Remote Control Car', description: 'High-speed RC with 2.4GHz remote, rechargeable, all-terrain tires. Ages 6+.', category: 'Toys', price: 2489, basePrice: 4149, stockQuantity: 100, imageURL: 'https://m.media-amazon.com/images/I/71wVNWPjS9L._SL500_.jpg', brand: 'SpeedRacer', tags: ['remote-control', 'car'], averageRating: 4.3, numReviews: 134, salesLast30Days: 37 },
    { name: 'Art Supply Kit for Kids', description: '150-piece: crayons, markers, colored pencils, watercolors + case. Ages 3+.', category: 'Toys', price: 2074, basePrice: 3734, stockQuantity: 130, imageURL: 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=500&h=400&fit=crop', brand: 'LittleArtist', tags: ['art', 'creative'], averageRating: 4.5, numReviews: 198, salesLast30Days: 43 },
    { name: 'Wooden Train Set', description: '50-piece classic wooden train set with bridge, station, trees. Ages 3+.', category: 'Toys', price: 2904, basePrice: 4979, stockQuantity: 80, imageURL: 'https://m.media-amazon.com/images/I/81tUeY5CPPL._SL500_.jpg', brand: 'WoodCraft', tags: ['wooden', 'train'], averageRating: 4.7, numReviews: 156, salesLast30Days: 35 },
    { name: 'Science Experiment Kit', description: '20+ hands-on experiments: volcanoes, crystals, slime. STEM learning. Ages 6+.', category: 'Toys', price: 2323, basePrice: 3983, stockQuantity: 95, imageURL: 'https://images.unsplash.com/photo-1628595351029-c2bf17511435?w=500&h=400&fit=crop', brand: 'SciKids', tags: ['science', 'STEM'], averageRating: 4.6, numReviews: 212, salesLast30Days: 44 },
    { name: 'Play Dough Mega Set', description: '24-color play dough set with molds, tools, and play mat. Non-toxic. Ages 2+.', category: 'Toys', price: 1244, basePrice: 2323, stockQuantity: 200, imageURL: 'https://m.media-amazon.com/images/I/81OqOyPMw7L._SL500_.jpg', brand: 'PlayFun', tags: ['play-dough', 'creative'], averageRating: 4.4, numReviews: 178, salesLast30Days: 51 },
    { name: 'Board Game Family Edition', description: 'Classic strategy board game for 2-6 players. Fun for all ages.', category: 'Toys', price: 1659, basePrice: 2904, stockQuantity: 120, imageURL: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=500&h=400&fit=crop', brand: 'GameNight', tags: ['board-game', 'family'], averageRating: 4.5, numReviews: 234, salesLast30Days: 58 },
    { name: 'Puzzle Set 1000 Pieces', description: 'Beautiful landscape puzzle. Premium thick pieces, poster included.', category: 'Toys', price: 1327, basePrice: 2323, stockQuantity: 140, imageURL: 'https://images.unsplash.com/photo-1494059980473-813e73ee784b?w=500&h=400&fit=crop', brand: 'PuzzleMaster', tags: ['puzzle', 'landscape'], averageRating: 4.3, numReviews: 145, salesLast30Days: 36 },
    { name: 'Outdoor Kite Dragon', description: 'Large dragon kite 150cm wingspan. Easy to fly, colorful design. Ages 5+.', category: 'Toys', price: 995, basePrice: 1908, stockQuantity: 160, seasonalTag: 'Spring', imageURL: 'https://m.media-amazon.com/images/I/71pOJPq+N7L._SL500_.jpg', brand: 'SkyFun', tags: ['kite', 'outdoor'], averageRating: 4.2, numReviews: 98, salesLast30Days: 29 },

    // ===== AUTOMOTIVE (10) =====
    { name: 'Car Phone Mount Pro', description: 'Universal magnetic, 360° rotation. Strong neodymium magnets.', category: 'Automotive', price: 996, basePrice: 2074, stockQuantity: 320, imageURL: 'https://m.media-amazon.com/images/I/61JWx+p-k4L._SL500_.jpg', brand: 'AutoGrip', tags: ['car', 'magnetic'], averageRating: 4.1, numReviews: 156, salesLast30Days: 44 },
    { name: 'Dash Cam 1080p HD', description: 'Full HD with night vision, G-sensor, loop recording, 170° wide angle.', category: 'Automotive', price: 3734, basePrice: 6639, stockQuantity: 75, imageURL: 'https://m.media-amazon.com/images/I/61UFq5zNkdL._SL500_.jpg', brand: 'SafeDrive', tags: ['dashcam', 'safety'], averageRating: 4.4, numReviews: 112, salesLast30Days: 28 },
    { name: 'Car Vacuum Cleaner', description: 'Handheld 8000Pa suction, HEPA filter. Wet/dry, USB rechargeable.', category: 'Automotive', price: 2489, basePrice: 4149, stockQuantity: 100, imageURL: 'https://m.media-amazon.com/images/I/71Zv56h9mQL._SL500_.jpg', brand: 'CleanAuto', tags: ['vacuum', 'portable'], averageRating: 4.2, numReviews: 87, salesLast30Days: 22 },
    { name: 'LED Interior Car Lights', description: '4-strip RGB LED kit with remote & app control. 48 LEDs, 16 million colors.', category: 'Automotive', price: 1493, basePrice: 2904, stockQuantity: 200, imageURL: 'https://m.media-amazon.com/images/I/71xFcNmFURL._SL500_.jpg', brand: 'AutoGlow', tags: ['LED', 'interior'], averageRating: 4.3, numReviews: 234, salesLast30Days: 56 },
    { name: 'Tire Pressure Gauge Digital', description: 'Digital tire gauge with backlit LCD. Accurate to 0.1 PSI. Auto shut-off.', category: 'Automotive', price: 829, basePrice: 1659, stockQuantity: 250, imageURL: 'https://m.media-amazon.com/images/I/71kSi2yaQIL._SL500_.jpg', brand: 'SafeDrive', tags: ['tire', 'gauge'], averageRating: 4.5, numReviews: 167, salesLast30Days: 43 },
    { name: 'Car Air Freshener Set', description: 'Pack of 6 premium vent clip air fresheners. Long-lasting natural scents.', category: 'Automotive', price: 746, basePrice: 1410, stockQuantity: 300, imageURL: 'https://m.media-amazon.com/images/I/71V7njL2nDL._SL500_.jpg', brand: 'FreshAuto', tags: ['air-freshener', 'scent'], averageRating: 4.1, numReviews: 198, salesLast30Days: 67 },
    { name: 'Steering Wheel Cover Leather', description: 'Genuine leather steering cover, anti-slip grip. Universal 15-inch fit.', category: 'Automotive', price: 1659, basePrice: 2904, stockQuantity: 130, imageURL: 'https://m.media-amazon.com/images/I/81vkx1R-p9L._SL500_.jpg', brand: 'AutoGrip', tags: ['steering', 'leather'], averageRating: 4.3, numReviews: 145, salesLast30Days: 34 },
    { name: 'Car Trunk Organizer', description: 'Foldable multi-compartment trunk organizer. Heavy-duty, waterproof base.', category: 'Automotive', price: 1908, basePrice: 3319, stockQuantity: 110, imageURL: 'https://m.media-amazon.com/images/I/81JtKhNXY5L._SL500_.jpg', brand: 'AutoStore', tags: ['organizer', 'trunk'], averageRating: 4.4, numReviews: 112, salesLast30Days: 27 },
    { name: 'Emergency Car Kit', description: 'Roadside emergency kit: jumper cables, flashlight, first aid, tools. 65-piece.', category: 'Automotive', price: 2904, basePrice: 4979, stockQuantity: 70, imageURL: 'https://m.media-amazon.com/images/I/81x7mTVjJmL._SL500_.jpg', brand: 'SafeDrive', tags: ['emergency', 'kit'], averageRating: 4.6, numReviews: 89, salesLast30Days: 19 },
    { name: 'Windshield Sun Shade', description: 'Foldable UV-blocking sun shade. Keeps car cool. Universal fit, easy storage.', category: 'Automotive', price: 1161, basePrice: 2074, stockQuantity: 180, seasonalTag: 'Summer', imageURL: 'https://m.media-amazon.com/images/I/81dCIsDSLJL._SL500_.jpg', brand: 'CoolAuto', tags: ['sun-shade', 'UV'], averageRating: 4.2, numReviews: 178, salesLast30Days: 49 },
];

const discounts = [
    { code: 'WELCOME10', description: 'Welcome - 10% off first order', type: 'percentage', value: 10, maxDiscount: 4150, minOrderAmount: 2075, startDate: new Date(), endDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000), usageLimit: 1000, isActive: true, priority: 1 },
    { code: 'GOLD20', description: 'Gold member exclusive 20% off', type: 'percentage', value: 20, maxDiscount: 8300, minOrderAmount: 4150, startDate: new Date(), endDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000), usageLimit: 500, isActive: true, priority: 2 },
    { code: 'FLAT1245', description: '₹1,245 off on orders over ₹6,225', type: 'fixed', value: 1245, minOrderAmount: 6225, startDate: new Date(), endDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000), usageLimit: 2000, isActive: true, priority: 0 },
    { code: 'BLOOM25', description: 'Bloom & Buy special - 25% off fashion', type: 'percentage', value: 25, maxDiscount: 6225, applicableCategories: ['Clothing'], startDate: new Date(), endDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000), usageLimit: 800, isActive: true, priority: 1 },
    { code: 'SAVE415', description: '₹415 off any order', type: 'fixed', value: 415, minOrderAmount: 1245, startDate: new Date(), endDate: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000), usageLimit: 5000, isActive: true, priority: 0 },
];

async function seed() {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('Connected to MongoDB');
        await User.deleteMany({}); await Product.deleteMany({}); await Discount.deleteMany({}); await Seller.deleteMany({});
        console.log('Cleared data');

        const admin = new User({ name: 'Admin User', email: 'admin@bloomandbuy.com', passwordHash: 'Admin123!', role: 'admin' });
        await admin.save();
        const arpit = new User({ name: 'Arpit', email: 'arpit@example.com', passwordHash: 'Test123!', role: 'user' });
        await arpit.save();
        const rani = new User({ name: 'Rani', email: 'rani@example.com', passwordHash: 'Test123!', role: 'user' });
        await rani.save();

        // Create seller users
        const sellerUser1 = new User({ name: 'Rahul Sharma', email: 'rahul@techzone.com', passwordHash: 'Seller123!', role: 'seller' });
        await sellerUser1.save();
        const sellerUser2 = new User({ name: 'Priya Patel', email: 'priya@fashionhub.com', passwordHash: 'Seller123!', role: 'seller' });
        await sellerUser2.save();

        // Create seller profiles
        const seller1 = new Seller({
            user: sellerUser1._id,
            storeName: 'TechZone Electronics',
            storeDescription: 'Premium electronics and gadgets at best prices. We deal in headphones, speakers, smartwatches, and more.',
            storeLogo: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=200&h=200&fit=crop',
            phone: '9876543210',
            isActive: true,
            totalProducts: 10,
            totalSales: 0,
            totalRevenue: 0
        });
        await seller1.save();

        const seller2 = new Seller({
            user: sellerUser2._id,
            storeName: 'FashionHub India',
            storeDescription: 'Trendy clothing, accessories, and footwear for men and women. Quality fashion at affordable prices.',
            storeLogo: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=200&h=200&fit=crop',
            phone: '9876543211',
            isActive: true,
            totalProducts: 10,
            totalSales: 0,
            totalRevenue: 0
        });
        await seller2.save();

        console.log('✅ 2 sellers created');

        // Assign sellers to products: first 10 (Electronics) to seller1, next 10 (Clothing) to seller2
        // Remaining products have no seller (legacy/admin products)
        const productsToInsert = products.map((p, index) => {
            let pData = { ...p, approvalStatus: 'approved' };
            if (index < 10) return { ...pData, seller: seller1._id };      // Electronics -> TechZone
            if (index >= 10 && index < 20) return { ...pData, seller: seller2._id }; // Clothing -> FashionHub
            return pData; // No seller assigned — admin/marketplace products
        });

        await Product.insertMany(productsToInsert);
        console.log(`✅ ${products.length} products created (20 assigned to sellers)`);
        await Discount.insertMany(discounts);
        console.log(`✅ ${discounts.length} discount codes`);
        console.log('\n🌿 Bloom & Buy seed complete!');
        console.log('Accounts:');
        console.log('  Admin:  admin@bloomandbuy.com / Admin123!');
        console.log('  Buyer:  arpit@example.com / Test123!');
        console.log('  Buyer:  rani@example.com / Test123!');
        console.log('  Seller: rahul@techzone.com / Seller123!');
        console.log('  Seller: priya@fashionhub.com / Seller123!');
        process.exit(0);
    } catch (e) { console.error('Error:', e); process.exit(1); }
}
seed();
